/**
 * set-env.ts
 * ----------
 * Reads variables from .env (via dotenv) and writes them into the Angular
 * environment files so they are available at runtime.
 *
 * Usage:  npx ts-node scripts/set-env.ts
 *
 * SECURITY: This script reads from .env which must NEVER be committed.
 * Ensure .env is listed in .gitignore.
 */

import { writeFileSync } from 'fs';
import { resolve } from 'path';

// Load .env
// eslint-disable-next-line @typescript-eslint/no-require-imports
require('dotenv').config();

const supabaseUrl = process.env['SUPABASE_URL'] || '';
const supabaseKey = process.env['SUPABASE_ANON_KEY'] || '';

if (!supabaseUrl || !supabaseKey) {
  console.error(
    'ERROR: SUPABASE_URL and SUPABASE_ANON_KEY must be set in .env'
  );
  process.exit(1);
}

const envContent = (production: boolean) => `// AUTO-GENERATED by scripts/set-env.ts — do not edit manually
export const environment = {
  production: ${production},
  supabaseUrl: '${supabaseUrl}',
  supabaseKey: '${supabaseKey}',
};
`;

const targetDir = resolve(__dirname, '..', 'src', 'environments');
writeFileSync(resolve(targetDir, 'environment.ts'), envContent(false));
writeFileSync(resolve(targetDir, 'environment.prod.ts'), envContent(true));

console.warn('Environment files written successfully.');
